# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:10
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('typeforms', '0002_auto_20170614_0339'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', django.contrib.postgres.fields.jsonb.JSONField(default={})),
                ('typeform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='typeforms.Typeform')),
            ],
        ),
    ]
