# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formresponse',
            name='token',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
