version: '3'

services:
  nginx:
    image: zkan/intage-dash-nginx
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - ./static:/static
      - ./media:/media

  app:
    image: zkan/intage-dash
    depends_on:
      - db
    entrypoint: /entrypoint.sh
    env_file: .env
    volumes:
      - ./static:/static
      - ./media:/media
    labels:
      description: "dash"

  db:
    image: postgres:9.6.2-alpine
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
