FROM python:3.6.1

RUN apt update && apt install -y netcat

RUN pip install Django==1.11.2 \
    pandas==0.20.2 \
    psycopg2==2.7.1 \
    requests==2.17.3 \
    uWSGI==2.0.15

ENV APPLICATION_ROOT /app/

RUN mkdir $APPLICATION_ROOT
COPY . $APPLICATION_ROOT
COPY ./compose/django/entrypoint-production.sh /entrypoint.sh
COPY ./compose/django/uwsgi.ini $APPLICATION_ROOT
RUN chmod +x /entrypoint.sh
WORKDIR $APPLICATION_ROOT

RUN pip install -r requirements.txt
