# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-13 04:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typeform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=50)),
                ('payload', django.contrib.postgres.fields.jsonb.JSONField(default=[])),
            ],
        ),
    ]
